name: Python CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install poetry
        POETRY_VIRTUALENVS_CREATE=false poetry install

    - name: Pre-commit checks
      run: |
        PYTHONFAULTHANDLER=1 pre-commit run --all-files

    - name: Run pytest
      run: |
        pytest

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

  release:
    runs-on: ubuntu-latest

    steps:
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Create package
      run: |
        cargo build --release --all-features

    - name: Zip release
      run: |
        zip -r build.zip target/release/libruststartracker.so

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build.zip
        asset_name: build.zip
        asset_content_type: application/zip
