
name: Release CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  make-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies and create source distribution
      run: |
        pip install maturin
        maturin sdist

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload sdist
      run: |
        for file in ./target/wheels/*; do
          echo "Uploading $file..."
          gh release upload "${{ github.ref_name }}" "$file" --clobber
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-python-wheels:
    name: Build Python Wheels
    strategy:
      matrix:
        architecture: [arm64, x86-64]
        python-version: ['3.10', '3.11', '3.12']

    runs-on: ${{ matrix.architecture == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}

    needs:
        - make-release

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and build the wheel
      run: |
        pip install maturin
        maturin build --release

    - name: Upload wheel
      run: |
        for file in ./target/wheels/*; do
          echo "Uploading $file..."
          gh release upload "${{ github.ref_name }}" "$file" --clobber
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/ruststartracker

    permissions:
      id-token: write

    needs:
        - build-python-wheels

    steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download wheels from GitHub Release
      run: |
        mkdir -p dist
        gh release download ${{ github.ref_name }} -D dist/
        ls dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check distributions with Twine
      run: |
        pip install twine
        twine check dist/*

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
