
name: Release CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  make-release:
    name: Create Release
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

  deploy-rust-crate:
    name: Deploy Rust Crate
    runs-on: ubuntu-22.04

    env:
      TARGET: real  # "test" for tests, "real" for production

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libclang-dev libopencv-dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Build and publish rust crate dry-run
      if: env.TARGET == 'test'
      run: |
        echo "${{ secrets.CRATESIO_KEY }}" | cargo login
        cargo publish --allow-dirty --dry-run
      env:
        CRATESIO_KEY: ${{ secrets.CRATESIO_KEY }}

    - name: Build and publish rust crate
      if: env.TARGET == 'real'
      run: |
        echo "${{ secrets.CRATESIO_KEY }}" | cargo login
        cargo publish --allow-dirty
      env:
        CRATESIO_KEY: ${{ secrets.CRATESIO_KEY }}

  build-python-sdist:
    name: Build Python sdist
    runs-on: ubuntu-22.04

    needs:
        - make-release

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libclang-dev libopencv-dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies and create source distribution
      run: |
        pip install poetry
        poetry build --format sdist
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Upload sdist
      run: |
        for file in ./dist/*; do
          echo "Uploading $file..."
          gh release upload "${{ github.ref_name }}" "$file" --clobber
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-python-wheels:
    name: Build Python Wheels
    strategy:
      matrix:
        architecture: [arm64, x86-64]
        python-version: ['3.10', '3.11', '3.12']

    runs-on: ${{ matrix.architecture == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}

    needs:
        - make-release

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libclang-dev build-essential cmake git pkg-config

    - name: Install OpenCV dependencies
      run: |
        git clone --branch 4.8.1 --depth 1 https://github.com/opencv/opencv.git
        cd opencv
        mkdir build && cd build
        cmake .. \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_TESTS=OFF \
          -DBUILD_PERF_TESTS=OFF \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_opencv_core=ON \
          -DBUILD_opencv_imgproc=ON \
          -DBUILD_opencv_highgui=OFF \
          -DBUILD_opencv_video=OFF \
          -DBUILD_opencv_features2d=OFF \
          -DBUILD_opencv_python_bindings_generator=OFF \
          -DBUILD_opencv_gapi=OFF \
          -DBUILD_opencv_calib3d=OFF \
          -DBUILD_opencv_imgcodecs=OFF \
          -DBUILD_opencv_ml=OFF \
          -DBUILD_opencv_photo=OFF \
          -DBUILD_opencv_dnn=OFF \
          -DBUILD_JPEG=OFF \
          -DBUILD_PNG=OFF \
          -DBUILD_TIFF=OFF \
          -DBUILD_WEBP=OFF \
          -DWITH_ITT=OFF \
          -DBUILD_ITT=OFF \
          -DWITH_IPP=OFF \
          -DWITH_IPPICV=OFF \
          -DBUILD_IPP_IW=OFF \
          -DBUILD_WITH_DYNAMIC_IPP=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/opt/opencv-static \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
          -DOPENCV_GENERATE_PKGCONFIG=ON
        make -j$(nproc)
        make install

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and build the wheel
      run: |
        pip install poetry
        poetry build --format wheel
      env:
        POETRY_VIRTUALENVS_CREATE: false
        RUST_STARTRACKER_OPENCV_LINK_STATIC: 1

    - name: Upload wheel
      run: |
        for file in ./dist/*; do
          echo "Uploading $file..."
          gh release upload "${{ github.ref_name }}" "$file" --clobber
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-22.04

    environment:
      name: pypi
      url: https://pypi.org/p/ruststartracker

    env:
      TARGET: real  # "test" for tests, "real" for production

    permissions:
      id-token: write

    needs:
        - build-python-wheels
        - build-python-sdist

    steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download wheels from GitHub Release
      run: |
        mkdir -p dist
        gh release download ${{ github.ref_name }} -D dist/
        ls dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check distributions with Twine
      run: |
        pip install twine
        twine check dist/*

    - name: Publish package distributions to PyPI
      if: env.TARGET == 'test'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/

    - name: Publish package distributions to PyPI
      if: env.TARGET == 'real'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
